### ISSUE TITLE
for odoo13 ? odoo12? or 14?

### ISSUE THREAD

**Issue by uptoheart** [zhuangweijia/load_echarts_to_odoo#1]
for which version? odoo 12 ? 13? 14?

**Comment by zhuangweijia** [comment]
for odoo14

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: uptoheart ***@***.***>
Sent: Thursday, April 15, 2021 9:42:47 PM
To: zhuangweijia/load_echarts_to_odoo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zhuangweijia/load_echarts_to_odoo] for odoo13 ? odoo12? or 14? (#1)


for which version

**Comment by uptoheart** [comment]
Thanks！
